# Generated by Django 3.2 on 2022-03-31 10:11

import blapi.utils.image
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.FileField(upload_to=blapi.utils.image.image_path),
        ),
    ]
