# Generated by Django 3.2 on 2022-03-30 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220330_0402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogimage',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_image', to='blog.blog'),
        ),
    ]
